name: Checking begginer class tennis lessons

env:
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check_beginner_class_availability:
    name: Check if there are available beginner tennis classes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setting up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Running script
        run: python check_tennis_schedule.py
